spring:
  application:
    name: webflux-course
  data:
    mongodb:
      uri: mongodb+srv://admin:<password>@webfluxcoursecluster.wzedsqr.mongodb.net/webflux-course?retryWrites=true&w=majority&appName=WebfluxCourseCluster